### ISSUE TITLE
关于速度和距离计算

### ISSUE THREAD

**Issue by chenchen0611** [404nofound/Monocular_Distance_Velocity_Detect#2]
请问一下，速度和距离计算是怎么得到的？😢

**Comment by 404nofound** [comment]
需已知相机内外参矩阵，相机架设高度、水平夹角，根据yolo识别车辆框的底部中心坐标，基于单目测距原理对世界、相机、图像、像素坐标系相互转换，计算相机点到目标车辆的横、纵向距离。速度是引入deep sort实现目标追踪后，根据框的大小变化计算距离变化，视频帧包含时间信息，用于计算速度。

**Comment by chenchen0611** [comment]
哦哦,知道了,感谢感谢.另外我想问一下,就是对于这种单目测距来说,做类似的小车无人驾驶在应对一些高校场景或者小范围场景下,功能能满足吗?另外还有您知道这种小车与车道线或者与路沿之间的距离是如何计算的吗?能给一些思路吗?老板让做个调研

**Comment by 404nofound** [comment]
可以考虑双目或者带深度信息的摄像头，准确度会高些。车道线就图像处理成黑白再透视转换成鸟瞰图，如果是要在视频中实时画出车道线，就是对图中的点进行多项式拟合计算车道线函数。如果只是测距，就以图片最下一行的车道或路沿所在的像素点位坐标通过相机内外参数计算。
