### ISSUE TITLE
关于跟踪与测速

### ISSUE THREAD

**Issue by ransheng11** [404nofound/Monocular_Distance_Velocity_Detect#5]
你好，请问下我只需要测距，跟踪和测速是我不需要的，我可以把这两个不要，对测距有影响吗，还有就是我相机架设应该是在正上方，这种角度对测距有影响吗

**Comment by 404nofound** [comment]
可以只测距，不影响。相机架设的高度和水平夹角要在代码里修改。只测距的话参考下面这个库：https://github.com/404nofound/Monocular_Distance_Detect

**Comment by ransheng11** [comment]
好的，谢谢
