### ISSUE TITLE
关于代码中相机内外参矩阵设置

### ISSUE THREAD

**Issue by zzt007** [404nofound/Monocular_Distance_Velocity_Detect#6]
您好，很棒的工作！请问代码中提供的camera_paramters.xlsx是不是得根据自己的实际情况进行修改，这样最终结果才比较精准？

**Comment by 404nofound** [comment]
是的，可以通过matlab、棋盘法去标定相机内参，外参的话根据相机坐标系和世界坐标系的映射关系来设置就行

**Comment by zzt007** [comment]
尝试了一下使用自己标定的内外参，结果都不太理想。另外想请问一下，为什么在我的检测片段中，处于自车正前方的车辆ID都会经常跳变呢？按道理YOLO检测应该是正常的，有点不解，具体可见下图。
![image](https://github.com/404nofound/Monocular_Distance_Velocity_Detect/assets/87843313/97677a77-260b-40ea-890b-d7d31e074581)
然后容易突变ID ，如下
![image](https://github.com/404nofound/Monocular_Distance_Velocity_Detect/assets/87843313/7def6072-5ac7-4368-940e-c01c8a07a0c3)

**Comment by 404nofound** [comment]
代码里还有相机的假设高度和水平角度参数要记得修改。目标追踪ReID是用的deepsort，这种距离远了之后特征不明显可能没法与之前的相匹配，一般我会把监测距离设的比较近。这套单目算法对道路环境条件的要求太高了，有坡度也不行的

**Comment by zzt007** [comment]
那两个参数我已经按实际情况修改，目前选取了一个比上两张图更简单的场景，效果还算能接受，谢谢。

**Comment by zzt007** [comment]
另想请问，关于使用matlab标定的问题，我是使用车载固定的单目相机拍摄了棋盘格图片，然后进行标定，这样通过matlab标定出来的外参（旋转矩阵、平移向量）应该是可以直接用的吧？但是我有点疑惑就是，标定的时候至少需要N>=3张图像，那么对于最后得到的旋转矩阵是 Nx3x3，平移向量是Nx3，那是只用选取对应的一组旋转矩阵+平移向量 组成外参矩阵 放到camera_paramters.xlsx里即可吗？

**Comment by 404nofound** [comment]
外参我没用标定的结果，我当时相机坐标系和世界坐标系除了存在一个高度差上的平移变换，其他就是简单的旋转变换。基本上矩阵都是0或1或-1这样组成的。

**Comment by 404nofound** [comment]
应该就自己去简单映射一下，外参矩阵我记得好像就是平移矩阵和旋转矩阵堆叠了一下，空白补了0

**Comment by zzt007** [comment]
那我的情况估计和大佬的差不多，现在也是直接用的你的外参，目测距离和输出的距离差不多，做定性分析应该够了
