### ISSUE TITLE
改為webcam相機實時辨識

### ISSUE THREAD

**Issue by kenny962508** [404nofound/Monocular_Distance_Velocity_Detect#7]
您好，不好意思想請問一下我使用您的程式並且將我自己的webcam相機內部參數校訂好後，我在track.py裡面將source改為0運行後出錯相機會開啟後馬上關閉，顯示以下成果，想請問是我哪裡需要修改嗎。

(mdvd) PS C:\Users\user\Desktop\Monocular_Distance_Velocity_Detect-main> python track.py --source 0 --yolo_model yolov5s.pt --deep_sort_model osnet_x1_0_imagenet --show-vid --save-vid --save-csv
C:\Users\user\Desktop\Monocular_Distance_Velocity_Detect-main\deep_sort/deep/reid\torchreid\metrics\rank.py:11: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  warnings.warn(

Available ReID models for automatic download
['resnet50_market1501', 'resnet50_dukemtmcreid', 'resnet50_msmt17', 'resnet50_fc512_market1501', 'resnet50_fc512_dukemtmcreid', 'resnet50_fc512_msmt17', 'mlfn_market1501', 'mlfn_dukemtmcreid', 'mlfn_msmt17', 'hacnn_market1501', 
'hacnn_dukemtmcreid', 'hacnn_msmt17', 'mobilenetv2_x1_0_market1501', 'mobilenetv2_x1_0_dukemtmcreid', 'mobilenetv2_x1_0_msmt17', 'mobilenetv2_x1_4_market1501', 'mobilenetv2_x1_4_dukemtmcreid', 'mobilenetv2_x1_4_msmt17', 'osnet_x
1_0_market1501', 'osnet_x1_0_dukemtmcreid', 'osnet_x1_0_msmt17', 'osnet_x0_75_market1501', 'osnet_x0_75_dukemtmcreid', 'osnet_x0_75_msmt17', 'osnet_x0_5_market1501', 'osnet_x0_5_dukemtmcreid', 'osnet_x0_5_msmt17', 'osnet_x0_25_market1501', 'osnet_x0_25_dukemtmcreid', 'osnet_x0_25_msmt17', 'resnet50_MSMT17', 'osnet_x1_0_MSMT17', 'osnet_x0_75_MSMT17', 'osnet_x0_5_MSMT17', 'osnet_x0_25_MSMT17', 'osnet_ibn_x1_0_MSMT17', 'osnet_ain_x1_0_MSMT17']
'git' 不是內部或外部命令、可執行的程式或批次檔。
YOLOv5  2024-6-26 torch 2.3.1+cpu CPU

Fusing layers... 
Model Summary: 213 layers, 7225885 parameters, 0 gradients
1/1: 0...  Success (inf frames 640x480 at 30.00 FPS)

C:\Users\user\Desktop\Monocular_Distance_Velocity_Detect-main\deep_sort/deep/reid\torchreid\utils\tools.py:43: UserWarning: No file found at "osnet_x1_0_imagenet"
  warnings.warn('No file found at "{}"'.format(fpath))
Successfully loaded imagenet pretrained weights from "C:\Users\user/.cache\torch\checkpoints\osnet_x1_0_imagenet.pth"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']
Model: osnet_x1_0
- params: 2,193,616
- flops: 978,878,352
frame_idx 0
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Monocular_Distance_Velocity_Detect-main\track.py", line 502, in <module>
    detect(opt)
  File "C:\Users\user\Desktop\Monocular_Distance_Velocity_Detect-main\track.py", line 244, in detect
    name_str=path.split('\\')[-1].split('.')[0]
AttributeError: 'list' object has no attribute 'split'

**Comment by 404nofound** [comment]
README.md中的Weights / Checkpoints环节需要使用我提供的权重文件来配置环境。另外你电脑似乎是CPU在运行程序，运行成功的话也会很卡顿。

**Comment by kenny962508** [comment]
您好我有将README.md中的Weights / Checkpoints配置了如下图所示。但将SOUCE改为0时还是依然无法成功运行，照样跑出跟上述一样的错误，如果使用MP4档时一切正常就只有要改为相机实时辨识时会出错，想请问是我哪边弄错了吗，再烦请大佬解惑。
![螢幕擷取畫面 2024-07-02 204902](https://github.com/404nofound/Monocular_Distance_Velocity_Detect/assets/104261219/05fd09b6-89fd-4f76-b3f3-f4c91c1f7673)

**Comment by 404nofound** [comment]
之前理解错你意思了。错误是因为代码中name_str=path.split('\')[-1].split('.')[0]是用来提取文件名的，例如：c:\user\XX\desktop\video1.mp4 ——> video1, webcam肯定没有文件名，可以在代码里直接改成固定值试试，例如: name_str='Example'

**Comment by kenny962508** [comment]
成功了 非常感謝大佬 !!
