### ISSUE TITLE
改用webcam之後距離計算以及速度會錯誤

### ISSUE THREAD

**Issue by kenny962508** [404nofound/Monocular_Distance_Velocity_Detect#8]
大佬您好，不好意思再次打扰一下。
我上次成功依您的指导将程式改为可以实时USB相机的影像辨识。
但我在后续的实验当中发现不管我怎麼移動距离都会变为0而速度也会变成一个定值(如附图)
![螢幕擷取畫面 2024-07-16 205657](https://github.com/user-attachments/assets/4385a274-f464-48ce-8082-eccf824aed97)
我有试过将相机的内参调成我在Matlab上标定的成果依旧是这个情形，想请问可能是我哪边的设定错误了呢，谢谢您

**Comment by 404nofound** [comment]
这个项目测距测速的本质是通过不同帧（frame）下yolo识别出的框的长（或宽）与下一帧识别出同一物体的框的长（或宽）的变化量 与 两帧之间的时间 差量 来计算速度的。单目识别对与摄像头的水平角度与架设高度要求很高，你遇到的距离为0可能是被测物体太近了，这个目前没有很好的办法去优化，速度极大说明代码里计算速度那个公式的分母极小，可能要修改代码 让分母最小不低于0.1（但0.1这个量纲你要自己把握一下，我是估计的）。

**Comment by wuba-pat** [comment]
请问作者这个方法是基于Mobileye的地面假设方法么？

**Comment by 404nofound** [comment]
> 请问作者这个方法是基于Mobileye的地面假设方法么？

对的，就是基于这个做的
