### ISSUE TITLE
导入datasets遇到问题

### ISSUE THREAD

**Issue by latecherry** [404nofound/Monocular_Distance_Velocity_Detect#9]
您好，我遇到了一些问题，我不会解决：
Traceback (most recent call last):
  File "c:\Users\niyun\Desktop\distance\Monocular_Distance_Velocity_Detect-main\track.py", line 31, in <module>
    from yolov5.utils.datasets import LoadImages, LoadStreams, VID_FORMATS
ModuleNotFoundError: No module named 'yolov5.utils.datasets'sets import LoadImages, LoadStreams, VID_FORMATS
ModuleNotFoundError: No module named 'yolov5.utils.datasets'
<img width="803" alt="d38f18378f8b46ef1f627a3b0b3b246" src="https://github.com/user-attachments/assets/2981054f-128c-4df8-84a6-0a757b166add">
只有datasets遇到了问题，我不清楚如何解决，我不知道是否是yolo版本的问题
<img width="148" alt="{94660548-E1B9-40E5-9B01-9CA965EC2DF7}" src="https://github.com/user-attachments/assets/62955c09-d968-41bc-b0c9-6265225a5028">
谢谢您。

**Comment by latecherry** [comment]
我在jetson nano b01上也遇到了同样的问题

**Comment by 404nofound** [comment]
使用YoloV5-v5版本的相关代码及文件（如权重），在yolo github的target中查找历史版本。

**Comment by latecherry** [comment]
> 使用YoloV5-v5版本的相关代码及文件（如权重），在yolo github的target中查找历史版本。
好的谢谢您，我试一试

**Comment by latecherry** [comment]
谢谢您，我的问题已经解决了
